timekeep_v1_1/project/urls.py
from django.urls import path

from .views import projects, project, edit_entry, add_entry, delete_entry, delete_untracked_entry

app_name = 'project'

urlpatterns = [
    path('', projects, name='projects'),
    path('<int:project_id>/', project, name='project'),
    path('<int:project_id>/<int:entry_id>/edit/', edit_entry, name='edit_entry'),
    path('<int:project_id>/<int:entry_id>/delete/', delete_entry, name='delete_entry'),
    path('add_entry/<int:entry_id>/', add_entry, name='add_entry'),
    path('delete_untracked_entry/<int:entry_id>/', delete_untracked_entry, name='delete_untracked_entry'),


]

timekeep_v1_1/summary/urls.py
from django.urls import path, include
from . import views
from .views import summary, view_user

app_name = 'summary'

urlpatterns = [
    path('', summary, name='summary'),
    path('dashboard/', summary, name='dashboard'),
    path('view_user=<int:user_id>', view_user, name='view_user'),




]

timekeep_v1_1/team/urls.py
from django.urls import path
from .views import teams, add, team, edit, activate_team, invite, plans

app_name = 'team'

urlpatterns = [
    path('', teams, name='teams'),
    path('add/', add, name='add'),
    path('<int:team_id>/', team, name='team'),
    path('edit/', edit, name='edit'),
    path('invite/', invite, name='invite'),
    path('plans/', plans, name='plans'),
    path('activate_team/<int:team_id>/', activate_team, name='activate_team')
]

timekeep_v1_1/timekeep_v1_1/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from timetracking.timer import start_timer, stop_timer, discard_timer
from timetracking.views import (
    home,
    shop,
    acc,
    logout_request,
    accept_invitation,


)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('home/', include('summary.urls')),
    path('shop', shop, name='shop'),
    path('', include('subscriptions.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('logout/', logout_request, name='logout'),
    path('account/', acc, name='account'),
    path('accept_invitation/', accept_invitation, name='accept_invitation'),
    path('teams/', include('team.urls')),
    path('projects/', include('project.urls')),
    path("timetracking/timer/start_timer/", start_timer, name='start_timer'),
    path("timetracking/timer/stop_timer/", stop_timer, name='stop_timer'),
    path("timetracking/timer/discard_timer/", discard_timer, name='discard_timer'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

timekeep_v1_1/summary/models.py
from django.db import models

timekeep_v1_1/summary/views.py
import calendar
from datetime import datetime, timedelta, timezone

from dateutil.relativedelta import relativedelta
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404

from project.models import Entry
from project.models import Project
from team.models import Team, Invitation
from .utilities import get_time_for_user_and_date, \
    get_time_for_team_and_month, \
    get_time_for_user_and_month, \
    get_time_for_user_and_project_and_month, \
    get_time_for_user_and_team_month


# Create your views here.

@login_required
def summary(request):
    if not request.user.userprofile.active_team_id:
        teams = request.user.teams.exclude(pk=request.user.userprofile.active_team_id)
        invitations = Invitation.objects.filter(email=request.user.email, status=Invitation.INVITED)
        # create add team form for modal
        if request.method == 'POST':
            title = request.POST.get('add_team')

            if title:
                team = Team.objects.create(title=title, created_by=request.user)
                team.members.add(request.user)
                team.save()

                userprofile = request.user.userprofile
                userprofile.active_team_id = team.id
                userprofile.save()

                return redirect('summary:summary')

        return render(request, 'summary.html', {'teams': teams, 'invitations': invitations})

    team = get_object_or_404(Team, pk=request.user.userprofile.active_team_id, status=Team.ACTIVE)
    invitations = Invitation.objects.filter(email=request.user.email, status=Invitation.INVITED)
    all_projects = team.projects.all()
    members = team.members.all()

    num_days = int(request.GET.get('num_days', 0))
    date_user = datetime.now() - timedelta(days=num_days)
    date_entries = Entry.objects.filter(team=team, created_by=request.user, created_at__date=date_user, is_tracked=True)

    user_num_months = int(request.GET.get('user_num_months', 0))
    user_month = datetime.now() - relativedelta(months=user_num_months)

    for project in all_projects:
        project.time_for_user_and_project_and_month = get_time_for_user_and_project_and_month(team, project,
                                                                                              request.user, user_month)

    team_num_months = int(request.GET.get('team_num_months', 0))
    team_month = datetime.now() - relativedelta(months=team_num_months)

    for member in members:
        member.time_for_user_and_team_month = get_time_for_user_and_team_month(team, member, team_month)

    untracked_entries = Entry.objects.filter(team=team, created_by=request.user, is_tracked=False).order_by(
        '-created_at')

    for untracked_entry in untracked_entries:
        untracked_entry.minutes_since = int(
            (datetime.now(timezone.utc) - untracked_entry.created_at).total_seconds() / 60)

    monthly_days_count = 0
    cal = calendar.Calendar()

    for week in cal.monthdayscalendar(datetime.now().year, datetime.now().month):
        for i, day in enumerate(week):
            # not this month's day or a weekend
            if day == 0 or i >= 5:
                continue
            # or some other control if desired...
            monthly_days_count += 1
    monthly_hour_count = monthly_days_count * 8
    time_for_user_and_month = get_time_for_user_and_month(team, request.user, user_month)
    avg_hours_per_day = round(float(time_for_user_and_month / 60) / float(monthly_days_count), 2)
    hour_percent = round(100 * float(time_for_user_and_month / 60) / float(monthly_hour_count))

    context = {
        'team': team,
        'invitations': invitations,
        'all_projects': all_projects,
        'projects': all_projects[0:3],
        'date_entries': date_entries,
        'num_days': num_days,
        'date_user': date_user,
        'members': members,
        'untracked_entries': untracked_entries,
        'user_num_months': user_num_months,
        'user_month': user_month,
        'time_for_user_and_month': get_time_for_user_and_month(team, request.user, user_month),
        'time_for_user_and_date': get_time_for_user_and_date(team, request.user, date_user),
        'time_for_team_and_month': get_time_for_team_and_month(team, team_month),
        'team_num_months': team_num_months,
        'team_month': team_month,
        'monthly_days_count': monthly_days_count,
        'monthly_hour_count': monthly_hour_count,
        'avg_hours_per_day': avg_hours_per_day,
        'hour_percent': hour_percent,
    }
    # create add project form for modal
    team = get_object_or_404(Team, pk=request.user.userprofile.active_team_id, status=Team.ACTIVE)
    if request.method == 'POST':
        title = request.POST.get('add_proj')

        if title:
            project = Project.objects.create(team=team, title=title, created_by=request.user)
            project.save()

            return redirect('summary:summary')

    if 'home' and not 'dashboard' in request.META['PATH_INFO']:
        return render(request, 'summary.html', context)
    if 'dashboard' in request.META['PATH_INFO']:
        return render(request, 'dashboard.html', context)


@login_required
def view_user(request, user_id):
    team = get_object_or_404(Team, pk=request.user.userprofile.active_team_id, status=Team.ACTIVE)
    all_projects = team.projects.all()
    user = team.members.all().get(id=user_id)

    num_days = int(request.GET.get('num_days', 0))
    date_user = datetime.now() - timedelta(days=num_days)
    date_entries = Entry.objects.filter(team=team, created_by=request.user, created_at__date=date_user, is_tracked=True)

    user_num_months = int(request.GET.get('user_num_months', 0))
    user_month = datetime.now() - relativedelta(months=user_num_months)

    for project in all_projects:
        project.time_for_user_and_project_and_month = get_time_for_user_and_project_and_month(team, project,
                                                                                              request.user, user_month)

    context = {
        'team': team,
        'user': user,
        'all_projects': all_projects,
        'date_entries': date_entries,
        'num_days': num_days,
        'date_user': date_user,
        'user_num_months': user_num_months,
        'user_month': user_month,
        'time_for_user_and_month': get_time_for_user_and_month(team, request.user, user_month),
        'time_for_user_and_date': get_time_for_user_and_date(team, request.user, date_user),

    }

    return render(request, 'view_user.html', context)

timekeep_v1_1/summary/templates/dashboard.html
{% extends 'base.html' %}
{% include 'summary.html' %}

{% load format_min %}

{% block title %}Dashboard | {% endblock %}

{% block content %}
      <div class="d-flex flex-column align-items-stretch flex-shrink-0 bg-white" style="width: 83%; height: 93.3vh">
    <div class="d-flex align-items-center flex-shrink-0 p-3 link-dark text-decoration-none border-bottom">
        <svg class="bi pe-none me-2" width="30" height="24">
            <use xlink:href="#clock"/>
        </svg>

        <span class="fs-5 fw-semibold "><a class="active">Dashboard</a></span>

    </div>
        <div class="list-group list-group-flush scrollarea">


    <div class="list-group list-group-flush scrollarea">
        <div class="container">
            <div class="main-body">
            <div class="accordion mt-4" id="accordionPanelsStayOpenExample">
  <div class="accordion-item">
    <h2 class="accordion-header" id="panelsStayOpen-headingOne">
      <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseOne" aria-expanded="true" aria-controls="panelsStayOpen-collapseOne">
        Your time {% if num_days is 0 %}today{% else %}{{ date_user|date:"Y-m-d" }}{% endif %}
      </button>
    </h2>
    <div id="panelsStayOpen-collapseOne" class="accordion-collapse collapse show" aria-labelledby="panelsStayOpen-headingOne">
      <div class="accordion-body">
      {% if date_entries %}
        <table class="table">
          <thead>
          <tr>
            <th scope="row">Project</th>
            <th scope="row">Time</th>
          </tr>
          </thead>
          <tbody>
          {% for entry in date_entries %}
                    <tr>
            <td>{{ entry.project.title }}</td>
            <td>{{ entry.minutes|format_minutes }}</td>
          </tr>
          {% endfor %}
          </tbody>
          <tfoot>
            <tr>
              <th scope="row">Total</th>
              <td>{{ time_for_user_and_date|format_minutes }}</td>
            </tr>
          </tfoot>
        </table>
        {% else %}
      <h4>No entries today.</h4>
        {% endif %}

      <a href="?num_days={{ num_days|add:'1' }}">Previous</a>
      {% if num_days > 0 %}
      <a href="?num_days={{ num_days|add:'-1' }}">Next</a>
      {% endif %}
      </div>
    </div>
  </div>
  <div class="accordion-item">

    <h2 class="accordion-header" id="panelsStayOpen-headingTwo">

      <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseTwo" aria-expanded="true" aria-controls="panelsStayOpen-collapseTwo">
        Your time {% if user_num_months is 0 %}this month{% else %}{{ user_month|date:"Y-m" }}{% endif %}
      </button>
    </h2>

        <div id="panelsStayOpen-collapseTwo" class="accordion-collapse collapse show" aria-labelledby="panelsStayOpen-headingTwo">

            <div class="accordion-body">
      {% if time_for_user_and_month %}
        <table class="table">
          <thead>
          <tr>
            <th scope="row">Project</th>
            <th scope="row">Time</th>
          </tr>
          </thead>
          <tbody>
          {% for project in all_projects %}
          {% if project.time_for_user_and_project_and_month > 0 %}
                    <tr>
            <td>{{ project.title }}</td>
            <td>{{ project.time_for_user_and_project_and_month|format_minutes }}</td>
          </tr>
          {% endif %}
          {% endfor %}
          </tbody>
          <tfoot>
            <tr>
              <th scope="row">Total</th>
              <td>{{ time_for_user_and_month|format_minutes }}</td>
            </tr>
          </tfoot>
        </table>
        {% else %}
      <h4>No entries this month.</h4>
        {% endif %}

      <a href="?user_num_months={{ user_num_months|add:'1' }}">Previous</a>
      {% if user_num_months > 0 %}
      <a href="?user_num_months={{ user_num_months|add:'-1' }}">Next</a>
      {% endif %}
      </div>
    </div>
  </div>
{% if request.user == team.created_by %}
  <div class="accordion-item">
    <h2 class="accordion-header" id="panelsStayOpen-headingThree">
      <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseThree" aria-expanded="true" aria-controls="panelsStayOpen-collapseThree">
        Your team {% if team_num_months is 0 %}this month{% else %}{{ team_month|date:"Y-m" }}{% endif %}
      </button>
    </h2>
    <div id="panelsStayOpen-collapseThree" class="accordion-collapse collapse show" aria-labelledby="panelsStayOpen-headingThree">
      <div class="accordion-body">
   {% if request.user == team.created_by %}

      {% if time_for_team_and_month > 0 %}
        <table class="table">
          <thead>
          <tr>
            <th scope="row">Name</th>
            <th scope="row">Time</th>
          </tr>
          </thead>
          <tbody>
          {% for member in members %}

                    <tr>
            <td>{% firstof member.get_full_name member.username %}</td>
            <td>{{ member.time_for_user_and_team_month|format_minutes }}</td>
          </tr>
          {% endfor %}


          </tbody>

        </table>
        {% else %}
      <h4>No registered time for this team this month.</h4>
        {% endif %}
            <a href="?team_num_months={{ team_num_months|add:'1' }}">Previous</a>
      {% if team_num_months > 0 %}
      <a href="?team_num_months={{ team_num_months|add:'-1' }}">Next</a>
        {% endif %}
          {% endif %}

      </div>
    </div>
  </div>
          {% endif %}
    <div class="accordion-item">
        <h2 class="accordion-header" id="panelsStayOpen-headingFour">
          <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseFour" aria-expanded="true" aria-controls="panelsStayOpen-collapseFour">
            Untracked entries
          </button>
        </h2>
        <div id="panelsStayOpen-collapseFour" class="accordion-collapse collapse show" aria-labelledby="panelsStayOpen-headingFive">
          <div class="accordion-body">
                    <table class="table is-fullwidth" style="text-align: left;">
                        <thead>
                            <tr>
                                <th>Started</th>
                                <th>Time</th>
                                <th>Status</th>
                                <th>Add to project</th>
                                <th>Discard</th>
                            </tr>
                        </thead>

                        <tbody>
                            {% for entry in untracked_entries %}
                                <tr>
                                    <td>{{ entry.created_at }}</td>
                                    <td>
                                        {% if entry.minutes == 0 %}
                                            {{ entry.minutes_since|format_minutes }}
                                        {% else %}
                                            {{ entry.minutes|format_minutes }}
                                        {% endif %}
                                    </td>

                                    <td>{% if entry.minutes == 0 %}In progress{% else %}Untracked{% endif %}</td>

                                    <td>
                                        <a href="{% url 'project:add_entry' entry.id %}">Add to project</a>

                                    </td>
                                    <td>
                                        <a href="{% url 'project:delete_untracked_entry' entry.id %}">Delete</a>

                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>

                    </table>

          </div>
        </div>
    </div>


<!--    Spare Accordion Item-->

<!--    <div class="accordion-item">-->
<!--        <h2 class="accordion-header" id="panelsStayOpen-headingFive">-->
<!--          <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseFive" aria-expanded="false" aria-controls="panelsStayOpen-collapseFive">-->
<!--            Accordion Item #5-->
<!--          </button>-->
<!--        </h2>-->
<!--        <div id="panelsStayOpen-collapseFive" class="accordion-collapse collapse" aria-labelledby="panelsStayOpen-headingFive">-->
<!--          <div class="accordion-body">-->
<!--            <strong>This is the third item's accordion body.</strong> It is hidden by default, until the collapse plugin adds the appropriate classes that we use to style each element. These classes control the overall appearance, as well as the showing and hiding via CSS transitions. You can modify any of this with custom CSS or overriding our default variables. It's also worth noting that just about any HTML can go within the <code>.accordion-body</code>, though the transition does limit overflow.-->
<!--          </div>-->
<!--        </div>-->
<!--    </div>-->

</div>
        </div>
</div>
</div>
</div>
</div>


{% endblock %}

timekeep_v1_1/summary/templates/view_user.html
{% extends 'base.html' %}

{% load format_min %}

{% block title %}{% firstof user.get_full_name user.username %} | {% endblock %}

{% block content %}
<div class="d-flex flex-column align-items-stretch flex-shrink-0 bg-white" style="width: 83%; height: 94vh">
    <div class="d-flex align-items-center flex-shrink-0 p-3 link-dark text-decoration-none border-bottom">
        <svg class="bi pe-none me-2" width="30" height="24">
            <use xlink:href="#clock"/>
        </svg>

        <span class="fs-5 fw-semibold "><a class="active">{% firstof user.get_full_name user.username %}</a></span>

    </div>

    <div class="list-group list-group-flush scrollarea">

        <br>
        <div class="container">
            <div class="row">

                <div class="col-lg-4">
                    <div class="profile-card-4 z-depth-3">
                        <div class="card">
                            <div class="card-body text-center bg-light rounded-top">
                                <div class="user-box">
                                    <img src="{{ user.userprofile.get_avatar }}" class="rounded-circle me-2"
                                         alt="user avatar" width="90%">
                                </div>

                            </div>
                            <div class="card-body">
                                <div class="row">

                                    <div class="col-sm-5">
                                        <h6 class="mb-0">Full Name</h6>
                                    </div>
                                    <div class="col-sm-7 text-secondary">
                                        {{ user.get_full_name}}
                                    </div>
                                </div>
                                <hr>
                                <div class="row">
                                    <div class="col-sm-5">
                                        <h6 class="mb-0">Username</h6>
                                    </div>
                                    <div class="col-sm-7 text-secondary">
                                        {{ user.username }}
                                    </div>
                                </div>
                                <hr>
                                <div class="row">
                                    <div class="col-sm-5">
                                        <h6 class="mb-0">Email</h6>
                                    </div>
                                    <div class="col-sm-7 text-secondary">
                                        {{ user.email }}
                                    </div>
                                </div>
                                <hr>

                                <div class="row">
                                    <div class="col-sm-5">
                                        <h6 class="mb-0">Member since</h6>
                                    </div>
                                    <div class="col-sm-7 text-secondary">
                                        {{ user.date_joined|date }}
                                    </div>
                                </div>

                            </div>

                        </div>
                    </div>
                </div>


                <div class="col-lg-8">
                    <div>
                        <div class="card">
                            <div class="accordion" id="accordionPanelsStayOpenExample">
                                <div class="accordion-item">
                                    <h2 class="accordion-header" id="panelsStayOpen-headingOne">
                                        <button class="accordion-button" type="button" data-bs-toggle="collapse"
                                                data-bs-target="#panelsStayOpen-collapseOne" aria-expanded="true"
                                                aria-controls="panelsStayOpen-collapseOne">{% firstof user.get_full_name user.username %}'s time {% if num_days is 0 %}today{% else %}{{ date_user|date:"Y-m-d" }}{% endif %}
                                        </button>
                                    </h2>
                                    <div id="panelsStayOpen-collapseOne" class="accordion-collapse collapse show"
                                         aria-labelledby="panelsStayOpen-headingOne">
                                        <div class="accordion-body">
                                            {% if date_entries %}
                                            <table class="table">
                                                <thead>
                                                <tr>
                                                    <th scope="row">Project</th>
                                                    <th scope="row">Time</th>
                                                </tr>
                                                </thead>
                                                <tbody>
                                                {% for entry in date_entries %}
                                                <tr>
                                                    <td>{{ entry.project.title }}</td>
                                                    <td>{{ entry.minutes|format_minutes }}</td>
                                                </tr>
                                                {% endfor %}
                                                </tbody>
                                                <tfoot>
                                                <tr>
                                                    <th scope="row">Total</th>
                                                    <td>{{ time_for_user_and_date|format_minutes }}</td>
                                                </tr>
                                                </tfoot>
                                            </table>
                                            {% else %}
                                            <h4>No entries today.</h4>
                                            {% endif %}

                                            <a href="?num_days={{ num_days|add:'1' }}">Previous</a>
                                            {% if num_days > 0 %}
                                            <a href="?num_days={{ num_days|add:'-1' }}">Next</a>
                                            {% endif %}
                                        </div>
                                    </div>
                                </div>
                                <div class="accordion-item">

                                    <h2 class="accordion-header" id="panelsStayOpen-headingTwo">

                                        <button class="accordion-button" type="button" data-bs-toggle="collapse"
                                                data-bs-target="#panelsStayOpen-collapseTwo" aria-expanded="true"
                                                aria-controls="panelsStayOpen-collapseTwo">{% firstof user.get_full_name user.username %}'s time {% if user_num_months is 0 %}this month{% else %}{{ user_month|date:"Y-m" }}{% endif %}
                                        </button>
                                    </h2>

                                    <div id="panelsStayOpen-collapseTwo" class="accordion-collapse collapse show"
                                         aria-labelledby="panelsStayOpen-headingTwo">

                                        <div class="accordion-body">
                                            {% if time_for_user_and_month %}
                                            <table class="table">
                                                <thead>
                                                <tr>
                                                    <th scope="row">Project</th>
                                                    <th scope="row">Time</th>
                                                </tr>
                                                </thead>
                                                <tbody>
                                                {% for project in all_projects %}
                                                {% if project.time_for_user_and_project_and_month > 0 %}
                                                <tr>
                                                    <td>{{ project.title }}</td>
                                                    <td>{{ project.time_for_user_and_project_and_month|format_minutes }}
                                                    </td>
                                                </tr>
                                                {% endif %}
                                                {% endfor %}
                                                </tbody>
                                                <tfoot>
                                                <tr>
                                                    <th scope="row">Total</th>
                                                    <td>{{ time_for_user_and_month|format_minutes }}</td>
                                                </tr>
                                                </tfoot>
                                            </table>
                                            {% else %}
                                            <h4>No entries this month.</h4>
                                            {% endif %}

                                            <a href="?user_num_months={{ user_num_months|add:'1' }}">Previous</a>
                                            {% if user_num_months > 0 %}
                                            <a href="?user_num_months={{ user_num_months|add:'-1' }}">Next</a>
                                            {% endif %}
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>

{% endblock %}