timekeep_v1_1/project/urls.py
from django.urls import path

from .views import projects, project, edit_entry, add_entry, delete_entry, delete_untracked_entry

app_name = 'project'

urlpatterns = [
    path('', projects, name='projects'),
    path('<int:project_id>/', project, name='project'),
    path('<int:project_id>/<int:entry_id>/edit/', edit_entry, name='edit_entry'),
    path('<int:project_id>/<int:entry_id>/delete/', delete_entry, name='delete_entry'),
    path('add_entry/<int:entry_id>/', add_entry, name='add_entry'),
    path('delete_untracked_entry/<int:entry_id>/', delete_untracked_entry, name='delete_untracked_entry'),


]

timekeep_v1_1/summary/urls.py
from django.urls import path, include
from . import views
from .views import summary, view_user

app_name = 'summary'

urlpatterns = [
    path('', summary, name='summary'),
    path('dashboard/', summary, name='dashboard'),
    path('view_user=<int:user_id>', view_user, name='view_user'),




]

timekeep_v1_1/team/urls.py
from django.urls import path
from .views import teams, add, team, edit, activate_team, invite, plans

app_name = 'team'

urlpatterns = [
    path('', teams, name='teams'),
    path('add/', add, name='add'),
    path('<int:team_id>/', team, name='team'),
    path('edit/', edit, name='edit'),
    path('invite/', invite, name='invite'),
    path('plans/', plans, name='plans'),
    path('activate_team/<int:team_id>/', activate_team, name='activate_team')
]

timekeep_v1_1/timekeep_v1_1/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from timetracking.timer import start_timer, stop_timer, discard_timer
from timetracking.views import (
    home,
    shop,
    acc,
    logout_request,
    accept_invitation,


)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('home/', include('summary.urls')),
    path('shop', shop, name='shop'),
    path('', include('subscriptions.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('logout/', logout_request, name='logout'),
    path('account/', acc, name='account'),
    path('accept_invitation/', accept_invitation, name='accept_invitation'),
    path('teams/', include('team.urls')),
    path('projects/', include('project.urls')),
    path("timetracking/timer/start_timer/", start_timer, name='start_timer'),
    path("timetracking/timer/stop_timer/", stop_timer, name='stop_timer'),
    path("timetracking/timer/discard_timer/", discard_timer, name='discard_timer'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

timekeep_v1_1/team/models.py
from django.db import models
from django.contrib.auth.models import User


class Plan(models.Model):
    title = models.CharField(max_length=255)
    max_projects_per_team = models.IntegerField(default=0)
    max_members_per_team = models.IntegerField(default=0)
    price = models.IntegerField(default=0)
    is_default = models.BooleanField(default=False)

    def __str__(self):
        return self.title

class Team(models.Model):
    ACTIVE = 'active'
    DELETED = 'deleted'

    CHOICES_STATUS = (
        (ACTIVE, 'Active'),
        (DELETED, 'Deleted')
    )

    PLAN_ACTIVE = 'active'
    PLAN_CANCELED = 'canceled'

    CHOICES_PLAN_STATUS = (
        (PLAN_ACTIVE, 'Active'),
        (PLAN_CANCELED, 'Canceled')
    )

    title = models.CharField(max_length=255)
    members = models.ManyToManyField(User, related_name='teams')
    created_by = models.ForeignKey(User, related_name='created_teams', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=10, choices=CHOICES_STATUS, default=ACTIVE)
    plan = models.ForeignKey(Plan, related_name='teams', on_delete=models.CASCADE, default=1)
    plan_end_date = models.DateTimeField(blank=True, null=True)
    plan_status = models.CharField(max_length=20, choices=CHOICES_PLAN_STATUS, default=PLAN_ACTIVE)

    class Meta:
        ordering = ['title']

    def __str__(self):
        return self.title


class Invitation(models.Model):
    #
    # Status

    INVITED = 'invited'
    ACCEPTED = 'accepted'

    CHOICES_STATUS = (
        (INVITED, 'Invited'),
        (ACCEPTED, 'Accepted')
    )

    team = models.ForeignKey(Team, related_name='invitations', on_delete=models.CASCADE)
    email = models.EmailField()
    code = models.CharField(max_length=20)
    status = models.CharField(max_length=20, choices=CHOICES_STATUS, default=INVITED)
    date_sent = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.email

timekeep_v1_1/team/views.py
import random
from datetime import datetime

from dateutil.relativedelta import relativedelta
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404

from project.models import Project
from summary.utilities import get_time_for_user_and_project_and_month
from .mail import send_invitation
from .models import Team, Invitation


@login_required
def add(request):
    if request.method == 'POST':
        title = request.POST.get('title')

        if title:
            team = Team.objects.create(title=title, created_by=request.user)
            team.members.add(request.user)
            team.save()

            userprofile = request.user.userprofile
            userprofile.active_team_id = team.id
            userprofile.save()

            return redirect('account')

    return render(request, 'team/add.html')


@login_required
def team(request, team_id):
    team = get_object_or_404(Team, pk=team_id, status=Team.ACTIVE, members__in=[request.user])
    invitations = team.invitations.filter(status=Invitation.INVITED)
    all_projects = team.projects.all()
    members = team.members.all()
    user_num_months = int(request.GET.get('user_num_months', 0))
    user_month = datetime.now() - relativedelta(months=user_num_months)

    for project in all_projects:
        project.time_for_user_and_project_and_month = get_time_for_user_and_project_and_month(team, project,
                                                                                              request.user, user_month)

    if request.method == 'POST':
        title = request.POST.get('add_proj')

        if title:
            project = Project.objects.create(team=team, title=title, created_by=request.user)
            project.save()

            return redirect('team:team', team_id=team.id)

        title = request.POST.get('edit_team')
        if title:
            team.title = title
            team.save()

            messages.info(request, 'The changes was saved')

            return redirect('team:team', team_id=team.id)

    context = {
        'team': team,
        'invitations': invitations,
        'all_projects': all_projects,
        'projects': all_projects,
        'members': members,

    }

    return render(request, 'team/team.html', context)


@login_required
def teams(request):
    teams = request.user.teams.exclude(pk=request.user.userprofile.active_team_id)
    invitations = Invitation.objects.filter(email=request.user.email, status=Invitation.INVITED)

    if request.method == 'POST':
        title = request.POST.get('add_team')

        if title:
            team = Team.objects.create(title=title, created_by=request.user)
            team.members.add(request.user)
            team.save()

            userprofile = request.user.userprofile
            userprofile.active_team_id = team.id
            userprofile.save()

            return redirect('team:teams')

    return render(request, 'team/teams.html', {'teams': teams, 'invitations': invitations})


@login_required
def edit(request):
    team = get_object_or_404(Team, pk=request.user.userprofile.active_team_id, status=Team.ACTIVE,
                             members__in=[request.user])

    if request.method == 'POST':
        title = request.POST.get('title')

        if title:
            team.title = title
            team.save()

            messages.info(request, 'The changes was saved')

            return redirect('team:team', team_id=team.id)

    return render(request, 'team/edit.html', {'team': team})


@login_required
def activate_team(request, team_id):
    team = get_object_or_404(Team, pk=team_id, status=Team.ACTIVE, members__in=[request.user])
    userprofile = request.user.userprofile
    userprofile.active_team_id = team.id
    userprofile.save()

    messages.info(request, 'The team was activated')

    return redirect(request.META['HTTP_REFERER'])


@login_required
def invite(request):
    team = get_object_or_404(Team, pk=request.user.userprofile.active_team_id, status=Team.ACTIVE)

    if request.method == 'POST':
        email = request.POST.get('email')

        if email:
            invitations = Invitation.objects.filter(team=team, email=email)

            if not invitations:
                code = ''.join(random.choice('abcdefghijklmnopqrstuvwxyz123456789') for i in range(8))
                invitation = Invitation.objects.create(team=team, email=email, code=code)

                messages.info(request, 'The user was invited')

                send_invitation(email, code, team)

                return redirect('team:team', team_id=team.id)
            else:
                messages.info(request, 'The users has already been invited')

    return render(request, 'team/invite.html', {'team': team})


@login_required
def plans(request):
    team = get_object_or_404(Team, pk=request.user.userprofile.active_team_id, status=Team.ACTIVE)

    context = {
        'team': team,

    }
    return render(request, 'team/plans.html', context)

timekeep_v1_1/team/templates/team/email_accepted_invitation.html
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        
        <title>TimeKeep</title>

        <style type="text/css">
            html {
                width: 100%;
            }

            body {
                width: 100%;
                font-family: Arial;
                font-size: 14px;
                background-color: #fff;
                color: #333;
            }

            a {
                color: #111;
            }
        </style>
    </head>

    <body>
        <table width="100%" cellspacing="0" cellpadding="0">
            <tr>
                <td><h1>TimeKeep</h1></td>
            </tr>

            <tr>
                <td>
                    <p>{{ invitation.email }} accepted your invitation.</p>
                </td>
            </tr>
        </table>
    </body>
</html>

timekeep_v1_1/team/templates/team/email_invitation.html
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        
        <title>TimeKeep</title>

        <style type="text/css">
            html {
                width: 100%;
            }

            body {
                width: 100%;
                font-family: Arial;
                font-size: 14px;
                background-color: #fff;
                color: #333;
            }

            a {
                color: #111;
            }
        </style>
    </head>

    <body>
        <table width="100%" cellspacing="0" cellpadding="0">
            <tr>
                <td><h1>TimeKeep- Invitation to {{ team.title }}</h1></td>
            </tr>

            <tr>
                <td>
                    <p>You have been invited to join {{ team.title }}</p>
                    <p>Click the link below to sign up or log in. Your team activation code is {{ code }}</p>
                </td>
            </tr>

            <tr>
                <td>
                    <a href="{{ acceptation_url }}">Accept invitation</a>
                </td>
            </tr>
        </table>
    </body>
</html>

timekeep_v1_1/team/templates/team/invite.html
{% extends 'base.html' %}

{% block title %}Invite | {{ team.title }} | {% endblock %}

{% block content %}
<div class="d-flex flex-column align-items-stretch flex-shrink-0 bg-white" style="width: 83%; height: 94vh">
    <div class="d-flex align-items-center flex-shrink-0 p-3 link-dark text-decoration-none border-bottom">
        <svg class="bi pe-none me-2" width="30" height="24">
            <use xlink:href="#clock"/>
        </svg>

        <span class="fs-5 fw-semibold "><a href="{% url 'team:teams' %}">Teams</a> /&nbsp;</span>
        <span class="fs-5 fw-semibold "><a href="{% url 'team:team' team.id %}">{{ team.title }}</a> /&nbsp;</span>
        <span class="fs-5 fw-semibold "><a class="active">Invite</a></span>

    </div>

    <div class="list-group list-group-flush scrollarea">
        <div class="container my-5">
            <div class="row p-4 pe-lg-0 pt-lg-5 align-items-center rounded-3 border shadow-lg">
                <div class="col-lg-5 p-3 p-lg-5 pt-lg-2">
                    <h4 class="display-6 fw-semibold lh-1">Invite to {{ team.title }}</h4>

                    <div class="col mt-5">
                        {% if team.plan.max_members_per_team > team.members.count %}
                        <form method="post" action=".">
                            {% csrf_token %}


                            <div class="field mt-2">
                                <label class="fw-semibold">Email</label>

                                <div class="control mt-1">
                                    <input type="email" class="input form-control" name="email"
                                           placeholder="example@example.com">
                                </div>
                            </div>


                            <div class="d-grid gap-2 d-md-flex justify-content-md-start mb-4 mb-lg-3">
                                <div class="form-group row mt-3">
                                    <div class="col-lg-12">
                                        <button class="btn btn-success active" type="submit">Send Invite</button>
                                    </div>
                                </div>
                            </div>
                        </form>
                        {% else %}
                        <div class="field mt-2">


                            This team has reached the limit of members.
                        </div>


                        <div class="d-grid gap-2 d-md-flex justify-content-md-start mb-4 mb-lg-3">
                            <div class="form-group row mt-3">
                                <div class="col-lg-12">
                                    {% if team.created_by == request.user %}
                                    <button type="button"
                                            class="btn btn-success px-4 me-md-2 w-100 fw-semibold"
                                            onclick="location.href='{% url 'team:plans' %}'">Upgrade plan
                                    </button>
                                    {% else %}
                                    <button type="button"
                                            class="btn btn-outline-secondary px-4 me-md-2 w-100 fw-semibold" disabled>
                                        Contact team
                                        owner to upgrade subscription.
                                    </button>
                                </div>
                            </div>
                        </div>

                        {% endif %}{% endif %}
                    </div>


                </div>
                <div class="col-lg-5 offset-lg-1 p-0 overflow-hidden shadow-lg">
                    <img class="rounded-lg-3"
                         src="https://thumbs.dreamstime.com/b/stopwatch-timekeeper-hand-man-207832275.jpg" alt=""
                         width="720">
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block scripts %}


{% endblock %}

timekeep_v1_1/team/templates/team/team.html
{% extends 'base.html' %}

{% load format_min %}

{% block title %}{{ team.title }} | {% endblock %}

{% block content %}
<div class="d-flex flex-column align-items-stretch flex-shrink-0 bg-white" style="width: 83%; height: 94vh">
    <div class="d-flex align-items-center flex-shrink-0 p-3 link-dark text-decoration-none border-bottom">
        <svg class="bi pe-none me-2" width="30" height="24">
            <use xlink:href="#clock"/>
        </svg>

        <span class="fs-5 fw-semibold "><a href="{% url 'team:teams' %}">Teams</a> /&nbsp;</span>
        <span class="fs-5 fw-semibold "><a class="active">{{ team.title }}</a></span>

    </div>
    <div class="list-group list-group-flush scrollarea">
        <div class="container">
            <div class="main-body">


                <div class="row gutters-sm mt-4">
                    <div class="col-md-4 mb-3">
                        <div class="card">


                            <div class="card-header py-2">
                                <h4 class="my-0 fw-semibold">Team {% if team == active_team %}(Active){% endif %}</h4>
                            </div>

                            <div class="card-body">

                                <h3 class="card-title">{{ team.title }}</h3>

                                <h4>{% if active_team.created_by == request.user %}(Owner){% else %}(Member){% endif %}</h4>

                            </div>
                            {% if team == active_team %}
                            {% if active_team.created_by == request.user %}

                            <div class="card-footer text-center">
                                <div class="row">
                                    <div>
                                        <button type="button" class="btn btn-outline-secondary mt-2"  data-bs-toggle="modal" data-bs-target="#editTeamModal">Edit team</button>
                                        <button type="button" class="btn btn-orange mt-2" onclick="location.href='{% url 'team:invite' %}'">Invite users</button>

                                    </div>
                                </div>
                            </div>
                            {% endif %}
                            {% else %}
                            <div class="card-footer text-center">
                                <div class="row">
                                    <div>


                                        <button type="button" class="btn btn-success px-4 me-md-2 w-100 fw-semibold" onclick="location.href='{% url 'team:activate_team' team.id %}'">Activate</button>


                                    </div>
                                </div>
                            </div>
                            {% endif %}


                        </div>

                        {% if invitations %}
                        <div class="card mt-3">
                            <div class="card-header py-2">
                                <h4 class="my-0 fw-semibold">Invited members</h4>
                            </div>

                            <div class="card-body">
                                {% for member in invitations %}
                                <p>{{ member.email }} - {{ member.date_sent|timesince }} ago</p>
                                {% endfor %}
                            </div>


                        </div>
                        {% endif %}

                        <div class="card mt-3">
                            <div class="card-header py-2">
                                <h4 class="my-0 fw-semibold">Members</h4>
                            </div>

                            <div class="card-body">
                                <ul class="list-group shadow-none">
                                {% for member in team.members.all %}
                                    <li class="list-group-item">
                                        <div class="list-details">
                                            <span><a href="{% url 'summary:view_user' member.id %}">{{ member.username }}</a></span>

                                        </div>
                                    </li>
                                </ul>
                                {% endfor %}
                            </div>


                        </div>
                                                <div class="card mt-3">
                            <div class="card-header py-2">
                                <h4 class="my-0 fw-semibold">Current plan</h4>
                            </div>
<div class="card-body">
                                <ul class="list-group shadow-none">
                                    <li class="list-group-item">
                                        <div class="list-icon">

                                        </div>
                                        <div class="list-details text-center">
                                            <span class="fw-semibold">{{ active_team.plan.title }}</span>
                                            <small></small>
                                        </div>
                                    </li>

                                    <li class="list-group-item">
                                        <div class="list-details">
                                            <span><b>Maximum projects per team:</b> {{ active_team.plan.max_projects_per_team }}</span>

                                        </div>
                                    </li>

                                                                        <li class="list-group-item">
                                        <div class="list-details">
                                            <span><b>Maximum members per team:</b> {{ active_team.plan.max_members_per_team }}</span>

                                        </div>
                                    </li>

                                    <li class="list-group-item">
                                        <div class="list-details">
                                            <span><b>Price:</b> {% if not active_team.plan.is_default %}{{ active_team.plan.price }}{% else %}Free{% endif %}</span>
                                        </div>
                                    </li>
                                </ul>

                            </div>




                        </div>

                    </div>
                    <div class="col-md-8">
                        <div class="card mb-3">
                            <div class="card-header py-2 container-fluid">
                                <div class="row">
                                    <div class="col-md-9">
                                        <h4 class="w-75 my-0 fw-semibold">Team projects</h4>
                                    </div>
                                    <div class="col-md-3 float-right">
                                        {% if active_team %}
                                            {% if team.plan.max_projects_per_team > team.projects.count %}
                                                    <button type="button"
                                                            class="btn btn-success px-4 me-md-2 w-100 fw-semibold"
                                                            data-bs-toggle="modal" data-bs-target="#addProjModal">Add
                                                        project
                                                    </button>
                                                {% else %}

                                                        {% if team.created_by == request.user %}
                                                            <button type="button"
                                                            class="btn btn-success px-4 me-md-2 w-100 fw-semibold"
                                                            onclick="location.href='{% url 'team:plans' %}'">Upgrade plan
                                                    </button>

                                                        {% else %}
                                                            <button type="button"
                                                            class="btn btn-outline-secondary px-4 me-md-2 w-100 fw-semibold" disabled>Contact team owner to upgrade subscription.
                                                    </button>
                                                        {% endif %}

                                                {% endif %}
                                        {% else %}
                                        <button type="button" class="btn btn-success px-4 me-md-2 w-100 fw-semibold" data-bs-toggle="modal" data-bs-target="#addTeamModal">Add team first</button>
                                        {% endif %}

                                    </div>
                                </div>

                            </div>
                            <div class="card-body">
                                {% if active_team.id %}
                                {% if projects %}
                                <div class="row row-cols-1 row-cols-md-3 mb-3 text-center">


                                    {% for project in projects %}
                                    <div class="col">
                                        <div class="card mb-4 rounded-3 shadow-sm">
                                            <div class="card-header py-2">
                                                <h4 class="my-0 fw-semibold">{{ project.title }}</h4>
                                            </div>

                                            <div class="card-body">

                                                <h5>{{ project.registered_time|format_minutes }}</h5>

                                            </div>
                                                                                        <div class="card-footer text-center">
                                <div class="row">
                                    <div>


                                        <button type="button" class="btn btn-outline-secondary px-4 me-md-2 w-100 fw-semibold" onclick="location.href='{% url 'project:project' project.id %}'">Details</button>


                                    </div>
                                </div>
                            </div>
                                        </div>
                                    </div>

                                    {% endfor %}


                                </div>
                                {% else %}
                                <h5>No projects yet</h5>
                                {% endif %}
                                {% endif %}
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="editTeamModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="vertical-alignment-helper">
            <div class="modal-dialog vertical-align-center">
                <div class="modal-content">
                    <div class="modal-header modal-header-own">
                        <h3 class="modal-title" id="exampleModalLabel">Edit Team</h3>
                        <!--        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>-->
                    </div>

                    <form method="POST">
                        {% csrf_token %}
                        <input name='add_team' style='display: none'>
                        <div class="form-floating">
                            <div>
                                <input type="text" class="form-control form-control-lg searchbox" id="id_title" name="edit_team" maxlength="150" placeholder="Team Title">

                            </div>
                        </div>


                        <div class="modal-footer">
                            <button type="submit" class="btn btn-success">Edit team</button>
                            <button type="button" class="btn btn-danger" data-bs-dismiss="modal">Close</button>

                        </div>
                    </form>

                </div>
            </div>
        </div>
    </div>
{% endblock %}