timekeep_v1_2/team/urls.py
from django.urls import path
from .views import add, team, edit, activate_team

app_name = 'team'

urlpatterns = [
    path('add/', add, name='add'),
    path('<int:team_id>/', team, name='team'),
    path('edit/', edit, name='edit'),
    path('activate_team/<int:team_id>/', activate_team, name='activate_team')
]

timekeep_v1_2/team/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Team(models.Model):

    ACTIVE = 'active'
    DELETED = 'deleted'

    CHOICES_STATUS = (
        (ACTIVE, 'Active'),
        (DELETED, 'Deleted')
    )

    title = models.CharField(max_length=255)
    members = models.ManyToManyField(User, related_name='teams')
    created_by = models.ForeignKey(User, related_name='created_teams', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=10, choices=CHOICES_STATUS, default=ACTIVE)

    class Meta:
        ordering = ['title']

    def __str__(self):
        return self.title

timekeep_v1_2/team/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.contrib import messages
# Create your views here.

from .models import Team


@login_required
def add(request):
    if request.method == 'POST':
        title = request.POST.get('title')

        if title:
            team = Team.objects.create(title=title, created_by=request.user)
            team.members.add(request.user)
            team.save()

            userprofile = request.user.userprofile
            userprofile.active_team_id = team.id
            userprofile.save()

            return redirect('account')

    return render(request, 'team/add.html')

@login_required
def team(request, team_id):
    team = get_object_or_404(Team, pk=team_id, status=Team.ACTIVE, members__in=[request.user])


    return render(request, 'team/team.html', {'team': team})

@login_required
def edit(request):
    team = get_object_or_404(Team, pk=request.user.userprofile.active_team_id, status=Team.ACTIVE, members__in=[request.user])

    if request.method == 'POST':
        title = request.POST.get('title')

        if title:
            team.title = title
            team.save()

            messages.info(request, 'The changes was saved')

            return redirect('team:team', team_id=team.id)

    return render(request, 'team/edit.html', {'team': team})

@login_required
def activate_team(request, team_id):
    team = get_object_or_404(Team, pk=team_id, status=Team.ACTIVE, members__in=[request.user])
    userprofile = request.user.userprofile
    userprofile.active_team_id = team.id
    userprofile.save()

    messages.info(request, 'The team was activated')

    return redirect('team:team', team_id=team.id)

timekeep_v1_2/team/templates/team/team.html
{% extends 'base.html' %}

{% block title %}{{ team.title }} | {% endblock %}

{% block content %}

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="#">Dashboard</a></li>
        <li class="breadcrumb-item"><a href="{% url 'account' %}">My account</a></li>
        <li class="breadcrumb-item active" aria-current="page"><a href="{% url 'team:team' team.id %}">{{ team.title }}</a></li>
    </ol>
</nav>

<div class="row">
    <h1>{{ team.title }}</h1>

    <hr>

    <h2>Members</h2>

    {% for member in team.members.all %}
        <p>{{ member.username }}</p>
    {% endfor %}

    {% if team.created_by == request.user %}
    <hr>
    <h3>Owner actions</h3>
    <div class="buttons">
        <a href="{% url 'team:edit' %}" class="btn btn-primary">Edit team</a>
    </div>

    <div class="buttons">
        <a href="{% url 'project:projects' %}" class="btn btn-primary">Projects</a>
    </div>
    {% endif %}
</div>

{% endblock %}