timekeep_v1_1/project/urls.py
from django.urls import path

from .views import projects, project, edit_entry, add_entry, delete_entry, delete_untracked_entry

app_name = 'project'

urlpatterns = [
    path('', projects, name='projects'),
    path('<int:project_id>/', project, name='project'),
    path('<int:project_id>/<int:entry_id>/edit/', edit_entry, name='edit_entry'),
    path('<int:project_id>/<int:entry_id>/delete/', delete_entry, name='delete_entry'),
    path('add_entry/<int:entry_id>/', add_entry, name='add_entry'),
    path('delete_untracked_entry/<int:entry_id>/', delete_untracked_entry, name='delete_untracked_entry'),


]

timekeep_v1_1/summary/urls.py
from django.urls import path, include
from . import views
from .views import summary, view_user

app_name = 'summary'

urlpatterns = [
    path('', summary, name='summary'),
    path('dashboard/', summary, name='dashboard'),
    path('view_user=<int:user_id>', view_user, name='view_user'),




]

timekeep_v1_1/team/urls.py
from django.urls import path
from .views import teams, add, team, edit, activate_team, invite, plans

app_name = 'team'

urlpatterns = [
    path('', teams, name='teams'),
    path('add/', add, name='add'),
    path('<int:team_id>/', team, name='team'),
    path('edit/', edit, name='edit'),
    path('invite/', invite, name='invite'),
    path('plans/', plans, name='plans'),
    path('activate_team/<int:team_id>/', activate_team, name='activate_team')
]

timekeep_v1_1/timekeep_v1_1/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from timetracking.timer import start_timer, stop_timer, discard_timer
from timetracking.views import (
    home,
    shop,
    acc,
    logout_request,
    accept_invitation,


)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('home/', include('summary.urls')),
    path('shop', shop, name='shop'),
    path('', include('subscriptions.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('logout/', logout_request, name='logout'),
    path('account/', acc, name='account'),
    path('accept_invitation/', accept_invitation, name='accept_invitation'),
    path('teams/', include('team.urls')),
    path('projects/', include('project.urls')),
    path("timetracking/timer/start_timer/", start_timer, name='start_timer'),
    path("timetracking/timer/stop_timer/", stop_timer, name='stop_timer'),
    path("timetracking/timer/discard_timer/", discard_timer, name='discard_timer'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

timekeep_v1_1/project/models.py
from django.db import models
from django.contrib.auth.models import User

from team.models import Team

class Project(models.Model):
    team = models.ForeignKey(Team, related_name='projects', on_delete=models.CASCADE)
    title = models.CharField(max_length=255)

    created_by = models.ForeignKey(User, related_name='projects', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return self.title

    def registered_time(self):
        return sum(entry.minutes for entry in self.entries.all())


class Entry(models.Model):
    team = models.ForeignKey(Team, related_name='entries', on_delete=models.CASCADE)
    project = models.ForeignKey(Project, related_name='entries', on_delete=models.CASCADE, blank=True, null=True)
    minutes = models.IntegerField(default=0)
    is_tracked = models.BooleanField(default=False)
    created_by = models.ForeignKey(User, related_name='entries', on_delete=models.CASCADE)
    created_at = models.DateTimeField()

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return '%s' % self.created_at

timekeep_v1_1/project/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from datetime import datetime

from .models import Project, Entry
from team.models import Team


@login_required
def projects(request):
    teams = Team.objects.filter(members=request.user)
    team = get_object_or_404(Team, pk=request.user.userprofile.active_team_id, status=Team.ACTIVE)
    project_team_id = Team.objects.filter(members=request.user).values_list('id', flat=True)
    projects = team.projects.all()

    if request.method == 'POST':
        title = request.POST.get('add_proj')

        if title:
            project = Project.objects.create(team=team, title=title, created_by=request.user)
            project.save()

            return redirect('project:projects')

    for x in project_team_id:
        projects_for_teams = Project.objects.filter(team_id=x)

    return render(request, 'project/projects.html',
                  {'team': team, 'projects': projects, 'project_team_id': project_team_id,
                   'projects_for_teams': projects_for_teams, 'teams': teams, })


@login_required
def project(request, project_id):
    team = get_object_or_404(Team, pk=request.user.userprofile.active_team_id, status=Team.ACTIVE)
    project = get_object_or_404(Project, team=team, pk=project_id)

    if request.method == 'POST':
        form_type = request.POST.get('type', None)
        if form_type == 'edit_projct':
            title = request.POST.get('edit_proj')

            if title:
                project.title = title
                project.save()

                messages.info(request, 'The changes was saved!')

                return redirect('project:project', project_id=project.id)

        if form_type == 'add_time':
            hours = int(request.POST.get('hours', 0))
            minutes = int(request.POST.get('minutes', 0))
            date = '%s %s' % (request.POST.get('date'), datetime.now().time())
            minutes_total = int(hours) * 60 + int(minutes)

            entry = Entry.objects.create(team=team, project=project, minutes=minutes_total, created_by=request.user,
                                         created_at=date, is_tracked=True)
            return redirect('project:project', project_id=project.id)
    return render(request, 'project/project.html', {'today': datetime.today(), 'team': team, 'project': project})





@login_required
def edit_entry(request, project_id, entry_id):
    team = get_object_or_404(Team, pk=request.user.userprofile.active_team_id, status=Team.ACTIVE)
    project = get_object_or_404(Project, team=team, pk=project_id)
    entry = get_object_or_404(Entry, pk=entry_id, team=team)

    if request.method == 'POST':
        hours = int(request.POST.get('hours', 0))
        minutes = int(request.POST.get('minutes', 0))
        date = '%s %s' % (request.POST.get('date'), datetime.now().time())

        entry.created_at = date
        entry.minutes = (hours * 60) + minutes
        entry.save()

        messages.info(request, 'The changes was saved!')

        return redirect('project:project', project_id=project.id)

    hours, minutes = divmod(entry.minutes, 60)

    context = {
        'team': team,
        'project': project,
        'entry': entry,
        'hours': hours,
        'minutes': minutes

    }

    return render(request, 'project/edit_entry.html', context)


@login_required
def add_entry(request, entry_id):
    team = get_object_or_404(Team, pk=request.user.userprofile.active_team_id, status=Team.ACTIVE)
    entry = get_object_or_404(Entry, pk=entry_id, team=team)
    projects = team.projects.all()

    if request.method == 'POST':
        hours = int(request.POST.get('hours', 0))
        minutes = int(request.POST.get('minutes', 0))
        project = request.POST.get('project')

        if project:
            entry.project_id = project
            entry.minutes = (hours * 60) + minutes
            entry.created_at = '%s %s' % (request.POST.get('date'), entry.created_at.time())
            entry.is_tracked = True
            entry.save()

            messages.info(request, 'The time was tracked')

            return redirect('home')
        else:
            messages.error(request, '"Project" can not be empty! Choose a project.')

    hours, minutes = divmod(entry.minutes, 60)

    context = {
        'hours': hours,
        'minutes': minutes,
        'team': team,
        'projects': projects,
        'entry': entry
    }

    return render(request, 'project/add_entry.html', context)


@login_required
def delete_entry(request, project_id, entry_id):
    team = get_object_or_404(Team, pk=request.user.userprofile.active_team_id, status=Team.ACTIVE)
    project = get_object_or_404(Project, team=team, pk=project_id)
    entry = get_object_or_404(Entry, pk=entry_id, team=team)
    entry.delete()

    messages.info(request, 'Entry was deleted!')

    return redirect('project:project', project_id=project.id)



@login_required
def delete_untracked_entry(request, entry_id):
    team = get_object_or_404(Team, pk=request.user.userprofile.active_team_id, status=Team.ACTIVE)

    entry = get_object_or_404(Entry, pk=entry_id, team=team)
    entry.delete()

    messages.info(request, 'Entry was deleted!')

    return redirect(request.META['HTTP_REFERER'])

timekeep_v1_1/project/templates/project/add_entry.html
{% extends 'base.html' %}

{% block title %}Add entry | {% endblock %}

{% block content %}
<div class="d-flex flex-column align-items-stretch flex-shrink-0 bg-white" style="width: 83%; height: 94vh">
    <div class="d-flex align-items-center flex-shrink-0 p-3 link-dark text-decoration-none border-bottom">
        <svg class="bi pe-none me-2" width="30" height="24">
            <use xlink:href="#clock"/>
        </svg>

        <span class="fs-5 fw-semibold "><a href="{% url 'project:projects' %}">Projects</a> /&nbsp;</span>
        <span class="fs-5 fw-semibold "><a class="active">Add entry</a></span>

    </div>

    <div class="list-group list-group-flush scrollarea">
<div class="container my-5">
    <div class="row p-4 pe-lg-0 pt-lg-5 align-items-center rounded-3 border shadow-lg">
        <div class="col-lg-5 p-3 p-lg-5 pt-lg-2">
                    <h4 class="display-6 fw-semibold lh-1">Register tracked time</h4>

      <div class="col mt-5">
<form method="post" action=".">
        {% csrf_token %}
                    <div class="col">
                        <label class="fw-semibold">Project name</label>
        <div class="form-group mt-1">
            <select class="form-control" name="project" v-model="project">
<option value="">Choose project</option>
                    {% for project in projects %}
                        <option value="{{ project.id }}">{{ project.title }}</option>
                    {% endfor %}
            </select>
        </div>
    </div>
    <div class="row mt-3">


                        <div class="col">
                            <label class="fw-semibold">Hours</label>
        <div class="form-group mt-1">
            <select class="form-control" name="hours">
<option value="0">0h</option>
                    {% for i in "x"|rjust:"23" %}
                        <option value="{{ forloop.counter }}"{% if hours == forloop.counter %} selected{% endif %}>{{ forloop.counter }}h</option>
                    {% endfor %}
            </select>
        </div>
    </div>

        <div class="col">
            <label class="fw-semibold">Minutes</label>
        <div class="form-group mt-1">
            <select class="form-control" name="minutes">
                    <option value="0">0m</option>
                    {% for i in "x"|rjust:"59" %}
                        <option value="{{ forloop.counter }}"{% if minutes == forloop.counter %} selected{% endif %}>{{ forloop.counter }}m</option>
                    {% endfor %}
            </select>
        </div>
    </div>








    </div>

    <div class="field mt-3">
        <label class="fw-semibold">Date</label>

        <div class="control mt-1">
            <input type="date" id="id_date" class="input form-control" name="date" value="{{ entry.created_at|date:'Y-m-d' }}" placeholder="yyyy-mm-dd">
        </div>
    </div>


       <div class="d-grid gap-2 d-md-flex justify-content-md-start mb-4 mb-lg-3">
                                                            <div class="form-group row mt-3">
                                                                <div class="col-lg-12">
                                                                   <button class="btn btn-success active" type="submit">Save Changes</button>
                                                                </div>
                                                            </div>
        </div>
        </form>
      </div>
        </div>
      <div class="col-lg-5 offset-lg-1 p-0 overflow-hidden shadow-lg">
          <img class="rounded-lg-3" src="https://thumbs.dreamstime.com/b/stopwatch-timekeeper-hand-man-207832275.jpg" alt="" width="720">
      </div>
    </div>
  </div>
    </div>    </div>
{% endblock %}

{% block scripts %}


{% endblock %}

timekeep_v1_1/project/templates/project/edit_entry.html
{% extends 'base.html' %}

{% block title %}Edit entry | {{ project.title }} | {% endblock %}

{% block content %}
<div class="d-flex flex-column align-items-stretch flex-shrink-0 bg-white" style="width: 83%; height: 94vh">
    <div class="d-flex align-items-center flex-shrink-0 p-3 link-dark text-decoration-none border-bottom">
        <svg class="bi pe-none me-2" width="30" height="24">
            <use xlink:href="#clock"/>
        </svg>

        <span class="fs-5 fw-semibold "><a href="{% url 'project:projects' %}">Projects</a> /&nbsp;</span>
        <span class="fs-5 fw-semibold "><a href="{% url 'project:project' project.id %}">{{ project.title }}</a> /&nbsp;</span>
        <span class="fs-5 fw-semibold "><a class="active">Edit entry</a></span>

    </div>

    <div class="list-group list-group-flush scrollarea">
        <div class="container my-5">
            <div class="row p-4 pe-lg-0 pt-lg-5 align-items-center rounded-3 border shadow-lg">
                <div class="col-lg-5 p-3 p-lg-5 pt-lg-2">
                    <h4 class="display-6 fw-semibold lh-1">Edit entry ({{ project.title }})</h4>

                    <div class="col mt-5">
                        <form method="post" action=".">
                        {% csrf_token %}

    <div class="row mt-3">


                        <div class="col">
                            <label class="fw-semibold">Hours</label>
        <div class="form-group mt-1">
            <select class="form-control" name="hours">
<option value="0">0h</option>
                    {% for i in "x"|rjust:"23" %}
                        <option value="{{ forloop.counter }}"{% if hours == forloop.counter %} selected{% endif %}>{{ forloop.counter }}h</option>
                    {% endfor %}
            </select>
        </div>
    </div>

        <div class="col">
            <label class="fw-semibold">Minutes</label>
        <div class="form-group mt-1">
            <select class="form-control" name="minutes">
                    <option value="0">0m</option>
                    {% for i in "x"|rjust:"59" %}
                        <option value="{{ forloop.counter }}"{% if minutes == forloop.counter %} selected{% endif %}>{{ forloop.counter }}m</option>
                    {% endfor %}
            </select>
        </div>
    </div>

    </div>

    <div class="field mt-3">
        <label class="fw-semibold">Date</label>

        <div class="control mt-1">
            <input type="date" id="id_date" class="input form-control" name="date" value="{{ entry.created_at|date:'Y-m-d' }}" placeholder="yyyy-mm-dd">
        </div>
    </div>


       <div class="d-grid gap-2 d-md-flex justify-content-md-start mb-4 mb-lg-3">
                                                            <div class="form-group row mt-3">
                                                                <div class="col-lg-12">
                                                                   <button class="btn btn-success active" type="submit">Save Changes</button>
                                                                </div>
                                                            </div>
        </div>
        </form>
      </div>
        </div>
      <div class="col-lg-5 offset-lg-1 p-0 overflow-hidden shadow-lg">
          <img class="rounded-lg-3" src="https://thumbs.dreamstime.com/b/stopwatch-timekeeper-hand-man-207832275.jpg" alt="" width="720">
      </div>
    </div>
  </div>
    </div>    </div>
{% endblock %}

{% block scripts %}


{% endblock %}

timekeep_v1_1/project/templates/project/project.html
{% extends 'base.html' %}

{% load format_min %}

{% block title %}{{ project.title }} | {% endblock %}

{% block content %}
<div class="d-flex flex-column align-items-stretch flex-shrink-0 bg-white" style="width: 83%; height: 94vh">
    <div class="d-flex align-items-center flex-shrink-0 p-3 link-dark text-decoration-none border-bottom">
        <svg class="bi pe-none me-2" width="30" height="24">
            <use xlink:href="#clock"/>
        </svg>

        <span class="fs-5 fw-semibold "><a href="{% url 'project:projects' %}">Projects</a> /&nbsp;</span>
        <span class="fs-5 fw-semibold "><a class="active">{{ project.title }}</a></span>

    </div>
    <div class="list-group list-group-flush scrollarea">
        <div class="container">
            <div class="main-body">

                <div class="row gutters-sm mt-4">
                    <div class="col-md-4 mb-3">
                        <div class="card">


                            <div class="card-header py-2">
                                <h4 class="my-0 fw-semibold">Project (Team:{{ active_team.title }})</h4>
                            </div>

                            <div class="card-body">

                                <h3 class="card-title">{{ project.title }}</h3>


                            </div>
                            {% if team == active_team %}
                            {% if active_team.created_by == request.user %}

                            <div class="card-footer text-center">
                                <div class="row">
                                    <div>
                                        <button type="button" class="btn btn-success px-4 me-md-2 w-100 fw-semibold" data-bs-toggle="modal" data-bs-target="#editProjModal">Edit project</button>

                                    </div>
                                </div>
                            </div>
                            {% endif %}
                            {% endif %}


                        </div>


<form method="post" action=".">
                        <div class="card mt-3">
                            <div class="card-header py-2">
                                <h4 class="my-0 fw-semibold">Register time</h4>
                            </div>

                            <div class="card-body">

            {% csrf_token %}
<input name='type' value='add_time' style='display: none'>

    <div class="row">


                        <div class="col">
                            <label class="fw-semibold">Hours</label>
        <div class="form-group mt-1">
            <select class="form-control" name="hours">
<option value="0">0h</option>
                    {% for i in "x"|rjust:"23" %}
                        <option value="{{ forloop.counter }}"{% if hours == forloop.counter %} selected{% endif %}>{{ forloop.counter }}h</option>
                    {% endfor %}
            </select>
        </div>
    </div>

        <div class="col">
            <label class="fw-semibold">Minutes</label>
        <div class="form-group mt-1">
            <select class="form-control" name="minutes">
                    <option value="0">0m</option>
                    {% for i in "x"|rjust:"59" %}
                        <option value="{{ forloop.counter }}"{% if minutes == forloop.counter %} selected{% endif %}>{{ forloop.counter }}m</option>
                    {% endfor %}
            </select>
        </div>
    </div>

    </div>

            <div class="field">
                <label class="fw-semibold mt-2">Date</label>

                <div class="control mt-1">
                    <input class="form-control" type="date" id="id_date" name="date" value="{{ today|date:'Y-m-d' }}"
                           placeholder="yyyy-mm-dd">
                </div>
            </div>




                            </div>
                            <div class="card-footer text-center">
                                <div class="row">
                                    <div>


<button class="btn btn-success px-4 me-md-2 w-100 fw-semibold" type="submit">Submit</button>

                                    </div>
                                </div>
                            </div>

                        </div>
                    </form>
                    </div>

                    <div class="col-md-8">
                        <div class="card mb-3">
                            <div class="card-header py-2 container-fluid">
                                <div class="row">
                                    <div class="col-md-9">
                                        <h4 class="w-75 my-0 fw-semibold">Logged entries</h4>
                                    </div>

                                </div>

                            </div>
                            <div class="card-body">
                                {% if project.entries.all %}
    <table class="table is-fullwidth" style="text-align: left;">
        <thead>
        <tr>
            <th>Date</th>
            <th>User</th>
            <th>Time</th>
            <th></th>
        </tr>
        </thead>

        <tbody>
        {% for entry in project.entries.all %}
        <tr>
            <td>{{ entry.created_at }}</td>
            <td><a href="{% url 'summary:view_user' entry.created_by.id %}">{% firstof entry.created_by.get_full_name entry.created_by.username %}</a></td>
            <td>{{ entry.minutes|format_minutes }}</td>
            <td>
                <a href="{% url 'project:edit_entry' project.id entry.id %}">Edit</a>
                <a href="{% url 'project:delete_entry' project.id entry.id %}">Delete</a>

            </td>
        </tr>
        {% endfor %}
        </tbody>

        <tfoot>
        <tr>
            <th colspan="2">Total</th>
            <th colspan="2">{{ project.registered_time|format_minutes }}</th>
        </tr>
        </tfoot>
    </table>
    {% else %}
    <p>No entries yet...</p>
    {% endif %}
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>


<div class="modal fade" id="editProjModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true" backdrop="false">
        <div class="vertical-alignment-helper">
            <div class="modal-dialog vertical-align-center">
                <div class="modal-content">
                    <div class="modal-header modal-header-own">
                        <h3 class="modal-title" id="exampleModalLabel">Edit Project</h3>
                        <!--        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>-->
                    </div>

                    <form method="POST">
                        {% csrf_token %}
                        <input name='type' value='edit_projct' style='display: none'>
                        <div class="form-floating">
                            <div>
                                <input type="text" class="form-control form-control-lg searchbox" name="edit_proj" maxlength="150" placeholder="Project Title">

                            </div>
                        </div>


                        <div class="modal-footer">
                            <button type="submit" class="btn btn-success">Edit project</button>
                            <button type="button" class="btn btn-danger" data-bs-dismiss="modal">Close</button>

                        </div>
                    </form>

                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

timekeep_v1_1/project/templates/project/projects.html
{% extends 'base.html' %}

{% load format_min %}

{% block title %}Projects | {% endblock %}

{% block content %}
<div class="d-flex flex-column align-items-stretch flex-shrink-0 bg-white" style="width: 83%; height: 94vh">
    <div class="d-flex align-items-center flex-shrink-0 p-3 link-dark text-decoration-none border-bottom">
        <svg class="bi pe-none me-2" width="30" height="24">
            <use xlink:href="#clock"/>
        </svg>

        <span class="fs-5 fw-semibold "><a class="active">Projects</a></span>


    </div>
    <div class="list-group list-group-flush scrollarea">
        <div class="container">
            <div class="main-body">

            {% for teamz in teams %}
                <div class="row gutters-sm mt-4">
                    <div class="col-md-4 mb-3">
                        <div class="card">


                            <div class="card-header py-2">
                                <h4 class="my-0 fw-semibold">{{ teamz.title }} {% if teamz == active_team %}(Active){% endif %}</h4>
                            </div>

                            <div class="card-body">
                                <ul class="list-group shadow-none">
                                    <li class="list-group-item">
                                        <div class="list-icon">

                                        </div>
                                        <div class="list-details">
                                            <span class="fw-semibold">Members</span>
                                            <small></small>
                                        </div>
                                    </li>
                                {% for member in teamz.members.all %}
                                    <li class="list-group-item">
                                        <div class="list-details">
                                            <span>{{ member.username }}</span>

                                        </div>
                                    </li>
                                </ul>
                                {% endfor %}
                            </div>
                            {% if teamz != active_team %}


                            <div class="card-footer text-center">
                                <div class="row">
                                    <div>


                                        <button type="button" class="btn btn-success px-4 me-md-2 w-100 fw-semibold" onclick="location.href='{% url 'team:activate_team' teamz.id %}'">Activate</button>


                                    </div>
                                </div>
                            </div>
                            {% endif %}


                        </div>


                    </div>
                    <div class="col-md-8">
                        <div class="card mb-3">
                            <div class="card-header py-2 container-fluid">
                                <div class="row">
                                    <div class="col-md-9">
                                        <h4 class="w-75 my-0 fw-semibold">{{ teamz.title }}'s projects</h4>
                                    </div>
                                    <div class="col-md-3 float-right">
                                        {% if active_team %}
                                            {% if team.plan.max_projects_per_team > team.projects.count %}
                                                    <button type="button"
                                                            class="btn btn-success px-4 me-md-2 w-100 fw-semibold"
                                                            data-bs-toggle="modal" data-bs-target="#addProjModal">Add
                                                        project
                                                    </button>
                                                {% else %}

                                                        {% if team.created_by == request.user %}
                                                        <button type="button"
                                                            class="btn btn-warning px-4 me-md-2 w-100 fw-semibold"
                                                            onclick="location.href='{% url 'team:plans' %}'">Upgrade plan
                                                    </button>

                                                        {% else %}
                                                            <button type="button"
                                                            class="btn btn-outline-secondary px-4 me-md-2 w-100 fw-semibold" disabled>Contact team owner to upgrade subscription.
                                                    </button>
                                                        {% endif %}

                                            {% endif %}
                                        {% else %}
                                        <button type="button" class="btn btn-success px-4 me-md-2 w-100 fw-semibold" data-bs-toggle="modal" data-bs-target="#addTeamModal">Add team first</button>
                                        {% endif %}

                                    </div>
                                </div>

                            </div>
                            <div class="card-body">


                                <div class="row row-cols-1 row-cols-md-3 mb-3 text-center">


                                    {% for project in teamz.projects.all %}
                                    <div class="col">
                                        <div class="card mb-4 rounded-3 shadow-sm">
                                            <div class="card-header py-2">
                                                <h4 class="my-0 fw-semibold">{{ project.title }}</h4>
                                            </div>

                                            <div class="card-body">

                                                <h5>{{ project.registered_time|format_minutes }}</h5>

                                            </div>
                                                                        {% if teamz == active_team %}
                                            <div class="card-footer text-center">
                                <div class="row">
                                    <div>


                                        <button type="button" class="btn btn-outline-secondary px-4 me-md-2 w-100 fw-semibold" onclick="location.href='{% url 'project:project' project.id %}'">Details</button>


                                    </div>
                                </div>
                            </div>
                                                                        {% endif %}
                                        </div>
                                    </div>
                                    {% empty %}
                                    <h5>No projects yet</h5>
                                    {% endfor %}


                                </div>



                            </div>
                        </div>
                    </div>

                </div>
                <hr>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
{% endblock %}